---
title: "IBA Anesthesia Comparison"
author: "Edna Chiang"
output: html_document
---

### Load Libraries
```{r}
library(ape)
library(dplyr)
library(equivalence)
library(phyloseq)
library(picante)
library(tidyr)

theme_set(theme_bw())
set.seed(1)
```

### Import Data
```{r}
# Link files
shared = "../mothur_output/final.shared"
taxonomy = "../mothur_output/final.taxonomy"
tree = "../mothur_output/final.tre"
# Import mothur data
mothurdata = import_mothur(
  mothur_shared_file = shared,
  mothur_constaxonomy_file = taxonomy,
  mothur_tree_file = tree)
# Add OTU column in taxonomy table
tax_table(mothurdata) <- cbind(tax_table(mothurdata), 
                               row.names(tax_table(mothurdata)))
# Rename taxonomy table columns
colnames(tax_table(mothurdata)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
# Remove OTUs that appear in < 3 samples
otu <- data.frame(otu_table(mothurdata))
otu.rem <- list()
for(i in 1:nrow(otu)){
  empty <- length(which(otu[i,] == 0))
    # Identifies # of samples w/o OTU
  if(empty > 54){
    # If OTU appears in < 3 samples
    otu.rem <- append(otu.rem, i)
      # Create list of OTUs that appear in only 1 sample
  }
}
otu.rem.row <- as.numeric(otu.rem)
  # Convert list to numeric
otu.rem.df <- otu[-otu.rem.row,]
  # Remove OTUs
otu.rem.tab <- otu_table(otu.rem.df, taxa_are_rows = T)
  # Convert trimmed OTU table to otu_table
# Add metadata
meta <- read.csv("metadata_extra.csv")
rownames(meta) <- meta$Sample
divsum <- read.table("../mothur_output/final.summary", header = T)
meta[,13:22] <- divsum[,3:12]
# Update phyloseq object
physeq <- merge_phyloseq(otu.rem.tab, tax_table(mothurdata), sample_data(meta),
                         phy_tree(mothurdata))
# Remove outliers
physeq <- subset_samples(physeq, ID != 3925)
physeq <- subset_samples(physeq, ID != 3916)
# Remove NA in "Anesthesia"
physeq <- subset_samples(physeq, Anesthesia != "NA")
# Subset out IBA
physeq.iba <- subset_samples(physeq, Group == "IBA")
```


### RTOST 
```{r}
# Code modified from Skarlupka, et al. (2019)
# https://doi.org/10.1186/s40104-019-0375-0
# Format OTU table
TOST.otu <- data.frame(t(data.frame(otu_table(physeq.iba))))
TOST.otu$Sample <- rownames(TOST.otu)
TOST.otu$Anesthesia <- "Isoflurane"
co2 <- c("CC1_883_I", "CC1_922_I", "CM1_883_I", "CM1_922_I")
for(i in 1:length(co2)){
  x <- which(TOST.otu$Sample == co2[i])
  TOST.otu$Anesthesia[x] <- "CO2"
}
# Separate by anesthesia
TOST.otu.iso <- TOST.otu[which(TOST.otu$Anesthesia == "Isoflurane"),]
TOST.otu.co2 <- TOST.otu[which(TOST.otu$Anesthesia == "CO2"),]
# Calculate mean OTUs for iso and pull out CO2 samples; remove Sample and Anesthesia cols I made
TOST.otu.iso.mean <- aggregate(TOST.otu.iso[ , 1: ( ncol(TOST.otu.iso)-2 ) ],
                               list(TOST.otu.iso$Anesthesia), mean)
TOST.otu.iso.mean <- TOST.otu.iso.mean[-1]
TOST.883C <- TOST.otu.co2[1,]
TOST.992C <- TOST.otu.co2[2,]
TOST.883M <- TOST.otu.co2[3,]
TOST.922M <- TOST.otu.co2[4,]
# Prepare data
TOST.otu.iso.t <- t(as.matrix(sapply(TOST.otu.iso.mean[,1:1618], as.numeric)))
TOST.883C.t <- t(as.matrix(sapply(TOST.883C[,1:1618], as.numeric)))
TOST.992C.t <- t(as.matrix(sapply(TOST.992C[,1:1618], as.numeric)))
TOST.883M.t <- t(as.matrix(sapply(TOST.883M[,1:1618], as.numeric)))
TOST.922M.t <- t(as.matrix(sapply(TOST.922M[,1:1618], as.numeric)))
### Explore Data
summary(as.vector(TOST.otu.iso.t))
length(which(TOST.otu.iso.t > 100, arr.ind = T))
  # 50 values above 100
jj <- scale(as.vector(TOST.otu.iso.t))
qqnorm(jj, main = "QQ-Plot for IBA Isoflurane")
abline(0, 1, col="red")
  # Not Normal
plot(density(as.vector(TOST.otu.iso.t)), main="Density Plot for IBA Isoflurane")
  # Skewed right
shapiro.test(TOST.otu.iso.t)
  # p-value < 2.2e-16
summary(as.vector(TOST.883C.t))
length(which(TOST.883C.t > 100, arr.ind = T))
  # 34 values above 100
jj <- scale(as.vector(TOST.883C.t))
qqnorm(jj, main = "QQ-Plot for 883C")
abline(0, 1, col="red")
  # Not Normal
plot(density(as.vector(TOST.883C.t)), main="Density Plot for 883C")
shapiro.test(TOST.883C.t)
  # p-value < 2.2e-16
summary(as.vector(TOST.992C.t))
length(which(TOST.992C.t > 100, arr.ind = T))
  # 42 values above 100
jj <- scale(as.vector(TOST.992C.t))
qqnorm(jj, main = "QQ-Plot for 992C")
abline(0, 1, col="red")
  # Not Normal
plot(density(as.vector(TOST.992C.t)), main="Density Plot for 992C")
shapiro.test(TOST.992C.t)
  # p-value < 2.2e-16
summary(as.vector(TOST.922M.t))
length(which(TOST.922M.t > 100, arr.ind = T))
  # 54 values above 100
jj <- scale(as.vector(TOST.922M.t))
qqnorm(jj, main = "QQ-Plot for 922M")
abline(0, 1, col="red")
  # Not Normal
plot(density(as.vector(TOST.922M.t)), main="Density Plot for 922M")
shapiro.test(TOST.922M.t)
  # p-value < 2.2e-16
summary(as.vector(TOST.883M.t))
length(which(TOST.883M.t > 100, arr.ind = T))
  # 36 values above 100
jj <- scale(as.vector(TOST.883M.t))
qqnorm(jj, main = "QQ-Plot for 883M")
abline(0, 1, col="red")
  # Not Normal
plot(density(as.vector(TOST.883M.t)), main="Density Plot for 883M")
shapiro.test(TOST.883M.t)
  # p-value < 2.2e-16
### Because data isn't Normally distributed, I'll use RTOST instead of TOST ###
### RTOST ###
rtost(TOST.otu.iso.t, TOST.883C.t, alpha = 0.05)
  # p-value = 2.535017e-29
  # Reject hypothesis that random & mean have non-equivalent means
rtost(TOST.otu.iso.t, TOST.992C.t, alpha = 0.05)
  # p-value = 2.535017e-29
  # Reject hypothesis that random & mean have non-equivalent means
rtost(TOST.otu.iso.t, TOST.922M.t, alpha = 0.05)
  # p-value = 2.535017e-29
  # Reject hypothesis that random & mean have non-equivalent means
rtost(TOST.otu.iso.t, TOST.883M.t, alpha = 0.05)
  # p-value = 2.535017e-29
  # Reject hypothesis that random & mean have non-equivalent means
```
