---
title: "Analysis"
author: "Edna Chiang"
date: "August 9, 2017"
output: html_document
---
 
### Load Libraries
```{r}
library(ape)
library(dplyr)
library(ggplot2)
library(gplots)
library(phangorn)
library(tidyr)
library(vegan)
library(phyloseq)
```

### Import Data
```{r}
# Link files
shared = "mothur_output/old/cecum.shared"
taxonomy = "mothur_output/old/cecum.taxonomy"


# Import mothur data
mothurdata = import_mothur(
  mothur_shared_file = shared,
  mothur_constaxonomy_file = taxonomy)

# Add OTU column in taxonomy table
tax_table(mothurdata) <- cbind(tax_table(mothurdata), 
                               row.names(tax_table(mothurdata)))

# Rename taxonomy table columns
colnames(tax_table(mothurdata)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")





### Try2 ###
# Link files
shared2 = "mothur_output/cecum2.shared"
taxonomy2 = "mothur_output/cecum2.taxonomy"


# Import mothur data
mothurdata2 = import_mothur(
  mothur_shared_file = shared2,
  mothur_constaxonomy_file = taxonomy2)

# Add OTU column in taxonomy table
tax_table(mothurdata2) <- cbind(tax_table(mothurdata2), 
                               row.names(tax_table(mothurdata2)))

# Rename taxonomy table columns
colnames(tax_table(mothurdata2)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

```

### Explore mothurdata object
```{r}
samp.sum <- data.frame(colSums(otu_table(mothurdata)))
colnames(samp.sum) <- "Sample_TotalSeqs"
samp.sum$sample <- row.names(samp.sum)
samp.sum <- arrange(samp.sum, Sample_TotalSeqs)

ggplot(samp.sum, aes(x=reorder(sample, Sample_TotalSeqs), y=Sample_TotalSeqs)) +
  ylab("Number of Sequences per Sample") +
  geom_bar(stat="identity", colour="black", fill="cornflowerblue") +
  xlab("Sample Name") +
  ggtitle("Total Number of Sequences per Sample") + 
  theme(axis.text.x = element_text(colour = "black", size=6, angle=45, hjust = 1,
                                   vjust = 1))

ggplot(data.frame(sum = sample_sums(mothurdata)), aes(sum)) + 
  geom_histogram(colour = "white", fill = "blue", bins=60) + 
  ggtitle("Sample read counts") + 
  xlab("total sequences")


# Min, Mean, Max of sample read counts
min(sample_sums(mothurdata))
mean(sample_sums(mothurdata))
median(sample_sums(mothurdata))
max(sample_sums(mothurdata))





### Try2 ###
samp.sum2 <- data.frame(colSums(otu_table(mothurdata2)))
colnames(samp.sum2) <- "Sample_TotalSeqs"
samp.sum2$sample <- row.names(samp.sum2)
samp.sum2 <- arrange(samp.sum2, Sample_TotalSeqs)

```
 

### Examine coverage
```{r}
cov <- read.table("mothur_output/6830.summary", header=T)
summary(cov$coverage)
bad <- which(cov$coverage < 0.95)
cov[bad, 3]
cov[bad,2]
sort(cov$coverage)

cov2 <- read.table("mothur_output/7940.summary", header=T)
summary(cov2$coverage)
bad2 <- which(cov2$coverage < 0.95)
cov2[bad2, 3]
cov2[bad2,2]
sort(cov2$coverage)

cov3 <- read.table("mothur_output/8334.summary", header=T)
summary(cov3$coverage)
bad3 <- which(cov3$coverage < 0.95)
cov3[bad3, 3]
cov3[bad3,2]
sort(cov3$coverage)

cov4 <- read.table("mothur_output/8509.summary", header=T)
summary(cov4$coverage)
bad4 <- which(cov4$coverage < 0.95)
cov4[bad4, 3]
cov4[bad4,2]
sort(cov4$coverage)


cov5 <- read.table("mothur_output/8589.summary", header=T)
summary(cov5$coverage)
bad5 <- which(cov5$coverage < 0.95)
cov5[bad5, 3]
cov5[bad5,2]
sort(cov5$coverage)


cov6 <- read.table("mothur_output/8855.summary", header=T)
summary(cov6$coverage)
bad6 <- which(cov6$coverage < 0.95)
cov6[bad6, 3]
cov6[bad6,2]
sort(cov6$coverage)


cov7 <- read.table("mothur_output/8900.summary", header=T)
summary(cov7$coverage)
bad7 <- which(cov7$coverage < 0.95)
cov7[bad7, 3]
cov7[bad7,2]
sort(cov7$coverage)


cov8 <- read.table("mothur_output/9027.summary", header=T)
summary(cov8$coverage)
bad8 <- which(cov8$coverage < 0.95)
cov8[bad8, 3]
cov8[bad8,2]
sort(cov8$coverage)

#### EVERYTHING ABOVE 95% COVERAGE!!!!! ####
cov9 <- read.table("mothur_output/9629.summary", header=T)
summary(cov9$coverage)
bad9 <- which(cov9$coverage < 0.95)
cov9[bad9, 3]
cov9[bad9,2]
sort(cov9$coverage)


cov10 <- read.table("mothur_output/10811.summary", header=T)
summary(cov10$coverage)
bad10 <- which(cov10$coverage < 0.95)
cov10[bad10, 3]
cov10[bad10,2]
sort(cov10$coverage)


### Attempt 2 ###
try2 <- read.table("mothur_output/cecum2.summary", header=T)
summary(try2$coverage)
bad2 <- which(try2$coverage < 0.95)
try2[bad2, 3]
try2[bad2,2]
sort(try2$coverage)



```