---
title: "Code_WildCaptive"
author: "Edna Chiang"
date: "5/10/2021"
output: html_document
---
### Load Libraries
```{r}
library(ape)
library(dplyr)
library(dunn.test)
library(ggplot2)
library(grid)
library(gridExtra)
library(phyloseq)
library(picante)
library(phytools)
library(tidyr)
library(vegan)

theme_set(theme_bw())
set.seed(1)
```

### Load Functions
```{r}
source('scripts/simper_pretty.R')
source('scripts/R_krusk.R')
source('scripts/misc.R')
```

### Import Data
```{r}
# Link files
shared = "mothur_output/final.shared"
taxonomy = "mothur_output/final.taxonomy"
tree = "mothur_output/final.tre"

# Import mothur data
mothurdata = import_mothur(
  mothur_shared_file = shared,
  mothur_constaxonomy_file = taxonomy,
  mothur_tree_file = tree)

# Add OTU column in taxonomy table
tax_table(mothurdata) <- cbind(tax_table(mothurdata), 
                               row.names(tax_table(mothurdata)))

# Rename taxonomy table columns
colnames(tax_table(mothurdata)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

# Add metadata
meta <- read.csv("metadata.csv")
rownames(meta) <- meta$Sample
divsum <- read.table("mothur_output/final.summary", header = T)
meta[,12:21] <- divsum[,3:12]

# Update phyloseq object
physeq <- merge_phyloseq(mothurdata, sample_data(meta))

# Subset out Summer Wild & Captive
phy.sum <- subset_samples(physeq, Season == "Summer")

# Remove OTUs that appear in < 3 samples
otu <- data.frame(otu_table(phy.sum))
otu.rem <- list()
for(i in 1:nrow(otu)){
  empty <- length(which(otu[i,] == 0))
    # Identifies # of samples w/o OTU
  if(empty > 19){
    # If OTU appears in < 3 samples
    otu.rem <- append(otu.rem, i)
      # Create list of OTUs that appear in only 1 sample
  }
}
otu.rem.row <- as.numeric(otu.rem)
  # Convert list to numeric
otu.rem.df <- otu[-otu.rem.row,]
  # Remove OTUs
otu.rem.tab <- otu_table(otu.rem.df, taxa_are_rows = T)
  # Convert trimmed OTU table to otu_table

# Update phyloseq object
phy.both <- merge_phyloseq(otu.rem.tab, sample_data(phy.sum), tax_table(phy.sum), phy_tree(phy.sum))

# Order factors
sample_data(phy.both)$Diet <- ordered(sample_data(phy.both)$Diet, levels = c("Captive", "Wild"))

# Calculate relative abundance
phy.both <- transform_sample_counts(phy.both, function(x){(x/sum(x))*100})

# Subset out unpaired samples
phy.pair <- subset_samples(phy.both, ID != 4057)
phy.pair <- subset_samples(phy.pair, ID != 3881)

# Subset by Sample Type
phy.con <- subset_samples(phy.pair, Sample_Type == "Content")
phy.muc <- subset_samples(phy.pair, Sample_Type == "Mucosa")

# Subset by Group
phy.wild <- subset_samples(phy.pair, Diet == "Wild")
phy.sum <- subset_samples(phy.pair, Diet == "Captive")

```


### Summer Wild & Captive - Compare Content and Mucosa - Alpha Div
```{r}
########## PD and MPD ##########

# Calculate Faith's phylogenetic diversity
pd.res <- pd(t(data.frame(otu_table(phy.pair))), phy_tree(phy.pair), 
             include.root = T)
pd.df <- data.frame(pd.res)

# Calculate MPD (Mean Pairwise Distance)
pd.dist <- cophenetic(phy_tree(phy.pair))
  # Calculate cophenetic distance

ses.mpd.res <- ses.mpd(t(data.frame(otu_table(phy.pair))), pd.dist, 
                       null.model = "taxa.labels", abundance.weighted = F, runs = 999)
  # Calculate MPD
  # This'll take a while to run-- be patient

mpd <- data.frame(ses.mpd.res)
  # Pull out MDP results


### Prepare data for plotting ###
mpd$SampleID <- row.names(mpd)
pd.res$SampleID <- row.names(pd.res)
  # Make sure all SampleID's match!


# Pull out first Stat of each test
# PD test = PD
# MPD test = SES (Standardized Effect Size)
pd.stats <- data.frame(pd.res$SampleID, pd.res$PD)
pd.stats$Measure <- rep("PD", nrow(pd.df))
colnames(pd.stats) <- c("Sample", "Stat", "Measure")
mpd.stats <- data.frame(mpd$SampleID, mpd$mpd.obs.z)
mpd.stats$Measure <- rep("MPD SES", nrow(pd.df))
colnames(mpd.stats) <- c("Sample", "Stat", "Measure")


### Prepare PD ###
pd.ready <- merge(pd.stats, meta, by = "Sample")
pd.sum <- pd.ready %>%
  group_by(Sample_Type) %>%
  summarize(Mean = mean(Stat),
            SE = se(Stat),
            SD = sd(Stat),
            Median = median(Stat))
pd.sum$YMAX <- pd.sum$Mean + pd.sum$SE
pd.sum$YMIN <- pd.sum$Mean - pd.sum$SE


### Prepare MPD ###
mpd.ready <- merge(mpd.stats, meta, by = "Sample")
mpd.sum <- mpd.ready %>%
  group_by(Sample_Type) %>%
  summarize(Mean = mean(Stat),
            SE = se(Stat),
            SD = sd(Stat),
            Median = median(Stat))
mpd.sum$YMAX <- mpd.sum$Mean + mpd.sum$SE
mpd.sum$YMIN <- mpd.sum$Mean - mpd.sum$SE


### TESTING PD & MPD ###
# For the paired tests, the tests assume that your samples are in the same order (same order of ID for both content and mucosa)
# Make sure you check ID orders!!!
### Test PD ###
hist(pd.ready$Stat, breaks=10)
qqnorm(pd.ready$Stat)
qqline(pd.ready$Stat)
shapiro.test(pd.ready$Stat)
  # p-value = 0.03328
  # Not Normal
wilcox.test(Stat ~ Sample_Type, data = pd.ready, paired = T)
  # p-value = 0.375

### Test MPD ###
hist(mpd.ready$Stat, breaks=10)
qqnorm(mpd.ready$Stat)
qqline(mpd.ready$Stat)
shapiro.test(mpd.ready$Stat)
  # p-value = 0.5624
  # Normal
t.test(Stat ~ Sample_Type, data = mpd.ready, paired = T)
  # p-value = 0.6379








########## Shannon ##########
adiv <- data.frame(sample_data(phy.pair))

### Testing ###
hist(adiv$shannon, breaks=10)
qqnorm(adiv$shannon)
qqline(adiv$shannon)
shapiro.test(adiv$shannon)
  # p-value = 0.1371
  # Normal
t.test(shannon ~ Sample_Type, data = adiv, paired = T)
  # p-value = 0.9063





########## Number of Unique OTUs ##########
otus <- data.frame(otu_table(phy.pair))
sampNames <- colnames(otus)
uniq.otus <- data.frame(matrix(nrow = nsamples(phy.pair), ncol = 2))
colnames(uniq.otus) <- c("Sample", "Unique_OTUs")
for(n in 1:nsamples(phy.pair)) {
  COL <- otus[,n]
  numUniq <- length(which(COL > 0))
  uniq.otus$Sample[n] <- sampNames[n]
  uniq.otus$Unique_OTUs[n] <- numUniq
}
uniq.otus$Sample_Type <- sample_data(phy.pair)$Sample_Type
rownames(uniq.otus) <- uniq.otus$Sample


### Testing ###
hist(uniq.otus$Unique_OTUs, breaks=10)
qqnorm(uniq.otus$Unique_OTUs)
qqline(uniq.otus$Unique_OTUs)
shapiro.test(uniq.otus$Unique_OTUs)
  # p-value =  0.08661
  # Normal
t.test(Unique_OTUs ~ Sample_Type, data = uniq.otus, paired = T)
  # P = 0.9807
```

### Summer Wild - Compare Content and Mucosa - Alpha Div
```{r}
########## PD and MPD ##########

# Calculate Faith's phylogenetic diversity
pd.wild.res <- pd(t(data.frame(otu_table(phy.wild))), phy_tree(phy.wild), 
             include.root = T)
pd.wild.df <- data.frame(pd.wild.res)

# Calculate MPD (Mean Pairwise Distance)
pd.wild.dist <- cophenetic(phy_tree(phy.wild))
  # Calculate cophenetic distance

ses.mpd.wild.res <- ses.mpd(t(data.frame(otu_table(phy.wild))), pd.wild.dist, 
                       null.model = "taxa.labels", abundance.weighted = F, runs = 999)
  # Calculate MPD
  # This'll take a while to run-- be patient

mpd.wild <- data.frame(ses.mpd.wild.res)
  # Pull out MDP results


### Prepare data for plotting ###
mpd.wild$SampleID <- row.names(mpd.wild)
pd.wild.res$SampleID <- row.names(pd.wild.res)
  # Make sure all SampleID's match!


# Pull out first Stat of each test
# PD test = PD
# MPD test = SES (Standardized Effect Size)
pd.wild.stats <- data.frame(pd.wild.res$SampleID, pd.wild.res$PD)
pd.wild.stats$Measure <- rep("PD", nrow(pd.wild.df))
colnames(pd.wild.stats) <- c("Sample", "Stat", "Measure")
mpd.wild.stats <- data.frame(mpd.wild$SampleID, mpd.wild$mpd.obs.z)
mpd.wild.stats$Measure <- rep("MPD SES", nrow(pd.wild.df))
colnames(mpd.wild.stats) <- c("Sample", "Stat", "Measure")


### Prepare PD ###
pd.wild.ready <- merge(pd.wild.stats, meta, by = "Sample")
pd.wild.sum <- pd.wild.ready %>%
  group_by(Sample_Type) %>%
  summarize(Mean = mean(Stat),
            SE = se(Stat),
            SD = sd(Stat),
            Median = median(Stat))
pd.wild.sum$YMAX <- pd.wild.sum$Mean + pd.wild.sum$SE
pd.wild.sum$YMIN <- pd.wild.sum$Mean - pd.wild.sum$SE


### Prepare MPD ###
mpd.wild.ready <- merge(mpd.wild.stats, meta, by = "Sample")
mpd.wild.sum <- mpd.wild.ready %>%
  group_by(Sample_Type) %>%
  summarize(Mean = mean(Stat),
            SE = se(Stat),
            SD = sd(Stat),
            Median = median(Stat))
mpd.wild.sum$YMAX <- mpd.wild.sum$Mean + mpd.wild.sum$SE
mpd.wild.sum$YMIN <- mpd.wild.sum$Mean - mpd.wild.sum$SE


### TESTING PD & MPD ###
# For the paired tests, the tests assume that your samples are in the same order (same order of ID for both content and mucosa)
# Make sure you check ID orders!!!
### Test PD ###
hist(pd.wild.ready$Stat, breaks=10)
qqnorm(pd.wild.ready$Stat)
qqline(pd.wild.ready$Stat)
shapiro.test(pd.wild.ready$Stat)
  # p-value = 0.9583
  # Normal
t.test(Stat ~ Sample_Type, data = pd.wild.ready, paired = T)
  # p-value = 0.411

### Test MPD ###
hist(mpd.wild.ready$Stat, breaks=10)
qqnorm(mpd.wild.ready$Stat)
qqline(mpd.wild.ready$Stat)
shapiro.test(mpd.wild.ready$Stat)
  # p-value = 0.596
  # Normal
t.test(Stat ~ Sample_Type, data = mpd.wild.ready, paired = T)
  # p-value = 0.07536








########## Shannon ##########
adiv.wild <- data.frame(sample_data(phy.wild))


### Testing ###
hist(adiv.wild$shannon, breaks=10)
qqnorm(adiv.wild$shannon)
qqline(adiv.wild$shannon)
shapiro.test(adiv.wild$shannon)
  # p-value = 0.4148
  # Normal
t.test(shannon ~ Sample_Type, data = adiv.wild, paired = T)
  # p-value = 0.2124







########## Number of Unique OTUs ##########
otus.wild <- data.frame(otu_table(phy.wild))
sampNames <- colnames(otus.wild)
uniq.otus.wild <- data.frame(matrix(nrow = nsamples(phy.wild), ncol = 2))
colnames(uniq.otus.wild) <- c("Sample", "Unique_OTUs")
for(n in 1:nsamples(phy.wild)) {
  COL <- otus.wild[,n]
  numUniq <- length(which(COL > 0))
  uniq.otus.wild$Sample[n] <- sampNames[n]
  uniq.otus.wild$Unique_OTUs[n] <- numUniq
}
uniq.otus.wild$Sample_Type <- sample_data(phy.wild)$Sample_Type
rownames(uniq.otus.wild) <- uniq.otus.wild$Sample



### Testing ###
hist(uniq.otus.wild$Unique_OTUs, breaks=10)
qqnorm(uniq.otus.wild$Unique_OTUs)
qqline(uniq.otus.wild$Unique_OTUs)
shapiro.test(uniq.otus.wild$Unique_OTUs)
  # p-value =  0.4452
  # Normal
t.test(Unique_OTUs ~ Sample_Type, data = uniq.otus.wild, paired = T)
  # p-value = 0.4103
```

### Summer Captive - Compare Content and Mucosa - Alpha Div
```{r}
########## PD and MPD ##########

# Calculate Faith's phylogenetic diversity
pd.sum.res <- pd(t(data.frame(otu_table(phy.sum))), phy_tree(phy.sum), 
             include.root = T)
pd.sum.df <- data.frame(pd.sum.res)

# Calculate MPD (Mean Pairwise Distance)
pd.sum.dist <- cophenetic(phy_tree(phy.sum))
  # Calculate cophenetic distance

ses.mpd.sum.res <- ses.mpd(t(data.frame(otu_table(phy.sum))), pd.sum.dist, 
                       null.model = "taxa.labels", abundance.weighted = F, runs = 999)
  # Calculate MPD
  # This'll take a while to run-- be patient

mpd.sum <- data.frame(ses.mpd.sum.res)
  # Pull out MDP results


### Prepare data for plotting ###
mpd.sum$SampleID <- row.names(mpd.sum)
pd.sum.res$SampleID <- row.names(pd.sum.res)
  # Make sure all SampleID's match!


# Pull out first Stat of each test
# PD test = PD
# MPD test = SES (Standardized Effect Size)
pd.sum.stats <- data.frame(pd.sum.res$SampleID, pd.sum.res$PD)
pd.sum.stats$Measure <- rep("PD", nrow(pd.sum.df))
colnames(pd.sum.stats) <- c("Sample", "Stat", "Measure")
mpd.sum.stats <- data.frame(mpd.sum$SampleID, mpd.sum$mpd.obs.z)
mpd.sum.stats$Measure <- rep("MPD SES", nrow(pd.sum.df))
colnames(mpd.sum.stats) <- c("Sample", "Stat", "Measure")


### Prepare PD ###
pd.sum.ready <- merge(pd.sum.stats, meta, by = "Sample")
pd.sum.sum <- pd.sum.ready %>%
  group_by(Sample_Type) %>%
  summarize(Mean = mean(Stat),
            SE = se(Stat),
            SD = sd(Stat),
            Median = median(Stat))
pd.sum.sum$YMAX <- pd.sum.sum$Mean + pd.sum.sum$SE
pd.sum.sum$YMIN <- pd.sum.sum$Mean - pd.sum.sum$SE


### Prepare MPD ###
mpd.sum.ready <- merge(mpd.sum.stats, meta, by = "Sample")
mpd.sum.sum <- mpd.sum.ready %>%
  group_by(Sample_Type) %>%
  summarize(Mean = mean(Stat),
            SE = se(Stat),
            SD = sd(Stat),
            Median = median(Stat))
mpd.sum.sum$YMAX <- mpd.sum.sum$Mean + mpd.sum.sum$SE
mpd.sum.sum$YMIN <- mpd.sum.sum$Mean - mpd.sum.sum$SE


### TESTING PD & MPD ###
# For the paired tests, the tests assume that your samples are in the same order (same order of ID for both content and mucosa)
# Make sure you check ID orders!!!
### Test PD ###
hist(pd.sum.ready$Stat, breaks=10)
qqnorm(pd.sum.ready$Stat)
qqline(pd.sum.ready$Stat)
shapiro.test(pd.sum.ready$Stat)
  # p-value = 0.03855
  # Not Normal
wilcox.test(Stat ~ Sample_Type, data = pd.sum.ready, paired = T)
  # p-value = 0.6875

### Test MPD ###
hist(mpd.sum.ready$Stat, breaks=10)
qqnorm(mpd.sum.ready$Stat)
qqline(mpd.sum.ready$Stat)
shapiro.test(mpd.sum.ready$Stat)
  # p-value = 0.06664
  # Normal
t.test(Stat ~ Sample_Type, data = mpd.sum.ready, paired = T)
  # p-value = 0.3535








########## Shannon ##########
adiv.sum <- data.frame(sample_data(phy.sum))


### Testing ###
hist(adiv.sum$shannon, breaks=10)
qqnorm(adiv.sum$shannon)
qqline(adiv.sum$shannon)
shapiro.test(adiv.sum$shannon)
  # p-value = 0.1935
  # Normal
t.test(shannon ~ Sample_Type, data = adiv.sum, paired = T)
  # p-value = 0.7101







########## Number of Unique OTUs ##########
otus.sum <- data.frame(otu_table(phy.sum))
sampNames <- colnames(otus.sum)
uniq.otus.sum <- data.frame(matrix(nrow = nsamples(phy.sum), ncol = 2))
colnames(uniq.otus.sum) <- c("Sample", "Unique_OTUs")
for(n in 1:nsamples(phy.sum)) {
  COL <- otus.sum[,n]
  numUniq <- length(which(COL > 0))
  uniq.otus.sum$Sample[n] <- sampNames[n]
  uniq.otus.sum$Unique_OTUs[n] <- numUniq
}
uniq.otus.sum$Sample_Type <- sample_data(phy.sum)$Sample_Type
rownames(uniq.otus.sum) <- uniq.otus.sum$Sample



### Testing ###
hist(uniq.otus.sum$Unique_OTUs, breaks=10)
qqnorm(uniq.otus.sum$Unique_OTUs)
qqline(uniq.otus.sum$Unique_OTUs)
shapiro.test(uniq.otus.sum$Unique_OTUs)
  # p-value =  0.188
  # Normal
t.test(Unique_OTUs ~ Sample_Type, data = uniq.otus.sum, paired = T)
  # p-value = 0.7764
```


### Adjust P-values
```{r}

### Paired T-test or Wilcoxon
p.adjust(c(0.98070,0.37500,0.63790,0.90630,0.41030,0.41100,0.07536,0.21240,0.77640,0.68750,0.35350,0.71010), method = "fdr")

  # 0.98070 0.82200 0.93168 0.98070 0.82200 0.82200 0.82200 0.82200 0.93168 0.93168 0.82200 0.93168
```