---
title: "Code_WildCaptive"
author: "Edna Chiang"
date: "5/10/2021"
output: html_document
---
### Load Libraries
```{r}
library(ape)
library(dplyr)
library(dunn.test)
library(ggplot2)
library(grid)
library(gridExtra)
library(phyloseq)
library(picante)
library(phytools)
library(tidyr)
library(vegan)

theme_set(theme_bw())
set.seed(1)
```

### Load Functions
```{r}
source('scripts/simper_pretty.R')
source('scripts/R_krusk.R')
source('scripts/misc.R')
```

### Import Data
```{r}
# Link files
shared = "mothur_output/final.shared"
taxonomy = "mothur_output/final.taxonomy"
tree = "mothur_output/final.tre"

# Import mothur data
mothurdata = import_mothur(
  mothur_shared_file = shared,
  mothur_constaxonomy_file = taxonomy,
  mothur_tree_file = tree)

# Add OTU column in taxonomy table
tax_table(mothurdata) <- cbind(tax_table(mothurdata), 
                               row.names(tax_table(mothurdata)))

# Rename taxonomy table columns
colnames(tax_table(mothurdata)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

# Add metadata
meta <- read.csv("metadata.csv")
rownames(meta) <- meta$Sample
divsum <- read.table("mothur_output/final.summary", header = T)
meta[,12:21] <- divsum[,3:12]

# Update phyloseq object
physeq <- merge_phyloseq(mothurdata, sample_data(meta))

# Subset out Summer Wild & Captive
phy.sum <- subset_samples(physeq, Season == "Summer")

# Remove OTUs that appear in < 3 samples
otu <- data.frame(otu_table(phy.sum))
otu.rem <- list()
for(i in 1:nrow(otu)){
  empty <- length(which(otu[i,] == 0))
    # Identifies # of samples w/o OTU
  if(empty > 19){
    # If OTU appears in < 3 samples
    otu.rem <- append(otu.rem, i)
      # Create list of OTUs that appear in only 1 sample
  }
}
otu.rem.row <- as.numeric(otu.rem)
  # Convert list to numeric
otu.rem.df <- otu[-otu.rem.row,]
  # Remove OTUs
otu.rem.tab <- otu_table(otu.rem.df, taxa_are_rows = T)
  # Convert trimmed OTU table to otu_table

# Update phyloseq object
phy.both <- merge_phyloseq(otu.rem.tab, sample_data(phy.sum), tax_table(phy.sum), phy_tree(phy.sum))

# Order factors
sample_data(phy.both)$Diet <- ordered(sample_data(phy.both)$Diet, levels = c("Captive", "Wild"))

# Calculate relative abundance
phy.both <- transform_sample_counts(phy.both, function(x){(x/sum(x))*100})

# Subset by Sample Type
phy.con <- subset_samples(phy.both, Sample_Type == "Content")
phy.muc <- subset_samples(phy.both, Sample_Type == "Mucosa")
```




### Content - Test Phyla Rel Abund
```{r}
# Merge samples with the same taxonomic rank
goodphy <- tax_glom(phy.con, taxrank="Phylum")

# Transform each merged phylum count to rel abund
phy99 <- transform_sample_counts(goodphy, function(x){(x/sum(x))*100})

# Remove any phyla with <1% rel abund
phy99 <- prune_taxa(taxa_sums(phy99) > 1, phy99)

# View ordered phyla - most abundant --> least abundant
# barplot(sort(taxa_sums(phy99),TRUE)[1:20]/nsamples(phy99),las=2,cex.axis=.7)
# Firmicutes, Bacteroidetes, Verrucomicrobia, Proteobacteria, Cyanobacteria, Unclassified, Tenericutes, Actinobacteria, Elusimicrobia

     


##### FIRMICUTES #####
fir.phy <- subset_taxa(phy99, Phylum == "Firmicutes")
fir.df <- data.frame(sample_data(fir.phy))
fir.df$RelAbund <- t(data.frame(otu_table(fir.phy)))

# Test normality
hist(fir.df$RelAbund, breaks=10)
qqnorm(fir.df$RelAbund)
qqline(fir.df$RelAbund)
shapiro.test(fir.df$RelAbund)
  # p-value = 0.1036
  # Normal
t.test(RelAbund ~ Diet, data = fir.df)
  # p-value = 0.1972




##### BACTEROIDETES #####
bac.phy <- subset_taxa(phy99, Phylum == "Bacteroidetes")
bac.df <- data.frame(sample_data(bac.phy))
bac.df$RelAbund <- t(data.frame(otu_table(bac.phy)))

# Test normality
hist(bac.df$RelAbund, breaks=10)
qqnorm(bac.df$RelAbund)
qqline(bac.df$RelAbund)
shapiro.test(bac.df$RelAbund)
  # p-value = 0.5738
  # Normal
t.test(RelAbund ~ Diet, data = bac.df)
  # p-value = 0.3764




##### Verrucomicrobia #####
ver.phy <- subset_taxa(phy99, Phylum == "Verrucomicrobia")
ver.df <- data.frame(sample_data(ver.phy))
ver.df$RelAbund <- t(data.frame(otu_table(ver.phy)))

# Test normality
hist(ver.df$RelAbund, breaks=10)
qqnorm(ver.df$RelAbund)
qqline(ver.df$RelAbund)
shapiro.test(ver.df$RelAbund)
  # p-value = 0.0001841
  # Not Normal
wilcox.test(RelAbund ~ Diet, data = ver.df)
  # p-value = 1




##### PROTEOBACTERIA #####
pro.phy <- subset_taxa(phy99, Phylum == "Proteobacteria")
pro.df <- data.frame(sample_data(pro.phy))
pro.df$RelAbund <- t(data.frame(otu_table(pro.phy)))

# Test normality
hist(pro.df$RelAbund, breaks=10)
qqnorm(pro.df$RelAbund)
qqline(pro.df$RelAbund)
shapiro.test(pro.df$RelAbund)
  # p-value = 0.06827
  # Normal
t.test(RelAbund ~ Diet, data = pro.df)
  # p-value = 0.01182




##### CYANOBACTERIA #####
# Pull out cyanos
cya.phy <- subset_taxa(phy99, Phylum == "Cyanobacteria")
cya.df <- data.frame(sample_data(cya.phy))
cya.df$RelAbund <- t(data.frame(otu_table(cya.phy)))

# Test normality
hist(cya.df$RelAbund, breaks=10)
qqnorm(cya.df$RelAbund)
qqline(cya.df$RelAbund)
shapiro.test(cya.df$RelAbund)
  # p-value = 0.005228
  # Not Normal
wilcox.test(RelAbund ~ Diet, data = cya.df)
  # p-value = 0.01212






##### TENERICUTES #####
ten.phy <- subset_taxa(phy99, Phylum == "Tenericutes")
ten.df <- data.frame(sample_data(ten.phy))
ten.df$RelAbund <- t(data.frame(otu_table(ten.phy)))

# Test normality
hist(ten.df$RelAbund, breaks=10)
qqnorm(ten.df$RelAbund)
qqline(ten.df$RelAbund)
shapiro.test(ten.df$RelAbund)
  # p-value = 0.03708
  # Not Normal
wilcox.test(RelAbund ~ Diet, data = ten.df)
  # p-value = 0.3572




##### ACTINOBACTERIA #####
act.phy <- subset_taxa(phy99, Phylum == "Actinobacteria")
act.df <- data.frame(sample_data(act.phy))
act.df$RelAbund <- t(data.frame(otu_table(act.phy)))

# Test normality
hist(act.df$RelAbund, breaks=10)
qqnorm(act.df$RelAbund)
qqline(act.df$RelAbund)
shapiro.test(act.df$RelAbund)
  # p-value = 0.05262
  # Normal
t.test(RelAbund ~ Diet, data = act.df)
  # p-value = 0.6397



##### ELUSIMICROBIA #####
elu.phy <- subset_taxa(phy99, Phylum == "Elusimicrobia")
elu.df <- data.frame(sample_data(elu.phy))
elu.df$RelAbund <- t(data.frame(otu_table(elu.phy)))

# Test normality
hist(elu.df$RelAbund, breaks=10)
qqnorm(elu.df$RelAbund)
qqline(elu.df$RelAbund)
shapiro.test(elu.df$RelAbund)
  # p-value = 3.247e-06
  # Not Normal
wilcox.test(RelAbund ~ Diet, data = elu.df)
  # p-value = 0.1817




##### UNCLASSIFIED #####
unc.phy <- subset_taxa(phy99, Phylum == "Bacteria_unclassified")
unc.df <- data.frame(sample_data(unc.phy))
unc.df$RelAbund <- t(data.frame(otu_table(unc.phy)))

# Test normality
hist(unc.df$RelAbund, breaks=10)
qqnorm(unc.df$RelAbund)
qqline(unc.df$RelAbund)
shapiro.test(unc.df$RelAbund)
  # p-value = 0.01209
  # Not Normal
wilcox.test(RelAbund ~ Diet, data = unc.df)
  # p-value = 0.2788



########## P-Adjust ##########
p.adjust(c(0.1972,0.3764,1,0.01182,0.01212,0.3572,0.6397,0.1817), method = "fdr")
  # 0.4437000 0.4839429 1.0000000 0.0545400 0.0545400 0.4839429 0.7196625 0.4437000 0.4839429





##### Summarize rel abund for table #####
phyla.sum <- psmelt(phy99)
phyla.sum.df <- phyla.sum %>%
  group_by(Diet, Phylum) %>%
  summarize(Mean = mean(Abundance),
            SE = se(Abundance))
phyla.sum.df$Phylum <- ordered(phyla.sum.df$Phylum, levels = c("Firmicutes", "Bacteroidetes", "Verrucomicrobia", "Proteobacteria", "Cyanobacteria", "Tenericutes", "Actinobacteria", "Elusimicrobia", "Bacteria_unclassified"))



#write.table(phyla.sum.df, "WildCaptive_Phyla.csv", sep=",")
```





### Content - Alpha-Diversity - Phylogenetic Diversity and SES MPD
```{r}
### Unweighted - Calculate phylogenetic diversity and MPD ###

# Calculate Faith's phylogenetic diversity
pd.res <- pd(t(data.frame(otu_table(phy.con))), phy_tree(phy.con), include.root = T)
pd.df <- data.frame(pd.res)

# Calculate MPD (Mean Pairwise Distance)
pd.dist <- cophenetic(phy_tree(phy.con))
  # Calculate cophenetic distance
ses.mpd.res <- ses.mpd(t(data.frame(otu_table(phy.con))), pd.dist, null.model = "taxa.labels", abundance.weighted = F, runs = 999)
  # Calculate MPD
  # This'll take a while to run-- be patient
#save(ses.mpd.res, file = "mpd.RData")
#load("mpd.RData")
mpd <- data.frame(ses.mpd.res)
  # Pull out MDP results


### Prepare data for plotting ###
mpd$SampleID <- row.names(mpd)
pd.res$SampleID <- row.names(pd.res)
  # Make sure all SampleID's match!

# Pull out first Stat of each test
# PD test = PD
# MPD test = SES (Standardized Effect Size)
pd.stats <- data.frame(pd.res$SampleID, pd.res$PD)
pd.stats$Measure <- rep("PD", nrow(pd.df))
colnames(pd.stats) <- c("Sample", "Stat", "Measure")
mpd.stats <- data.frame(mpd$SampleID, mpd$mpd.obs.z)
mpd.stats$Measure <- rep("MPD SES", nrow(pd.df))
colnames(mpd.stats) <- c("Sample", "Stat", "Measure")

        
########## TESTING PD & MPD ##########

### Test PD ###
hist(pd.ready$Stat, breaks=10)
qqnorm(pd.ready$Stat)
qqline(pd.ready$Stat)
shapiro.test(pd.ready$Stat)
  # p-value = 0.2589
  # Normal
t.test(Stat ~ Diet, data = pd.ready)
  # p-value = 0.0001161


 

### Test MPD ###
hist(mpd.ready$Stat, breaks=10)
qqnorm(mpd.ready$Stat)
qqline(mpd.ready$Stat)
shapiro.test(mpd.ready$Stat)
  # p-value = 0.4727
  # Normal
t.test(Stat ~ Diet, data = mpd.ready)
  # p-value = 0.07837
```



### Content - Alpha Diversity - Shannon & # OTUs
```{r}
adiv <- data.frame(sample_data(phy.con))


########## Shannon ##########
hist(adiv$shannon, breaks=10)
qqnorm(adiv$shannon)
qqline(adiv$shannon)
shapiro.test(adiv$shannon)
  # p-value = 0.1497
  # Normal
t.test(shannon ~ Diet, data = adiv)
  # p-value = 0.9401





########## Number of Unique OTUs ##########
otus <- data.frame(otu_table(phy.con))
sampNames <- colnames(otus)
uniq.otus <- data.frame(matrix(nrow = nsamples(phy.con), ncol = 2))
colnames(uniq.otus) <- c("Sample", "Unique_OTUs")
for(n in 1:nsamples(phy.con)) {
  COL <- otus[,n]
  numUniq <- length(which(COL > 0))
  uniq.otus$Sample[n] <- sampNames[n]
  uniq.otus$Unique_OTUs[n] <- numUniq
}
uniq.otus$Group <- sample_data(phy.con)$Group
rownames(uniq.otus) <- uniq.otus$Sample


hist(uniq.otus$Unique_OTUs, breaks=10)
qqnorm(uniq.otus$Unique_OTUs)
qqline(uniq.otus$Unique_OTUs)
shapiro.test(uniq.otus$Unique_OTUs)
  # p-value =  0.2577
  # Normal
t.test(Unique_OTUs ~ Group, data = uniq.otus)
  # p-value = 9.851e-05




###### Adjust a-div p-values ######
p.adjust(c(0.00009851, 0.0001161, 0.07837, 0.9401), method = "fdr")
  # 0.0002322 0.0002322 0.1044933 0.9401000
```


### Content - Alpha-Diversity Prepare Plots
```{r}
###### Unique # of OTUs ######

# Prepare data for plot
uniq.otus.sum <- uniq.otus %>%
  group_by(Group) %>%
  summarize(Mean = mean(Unique_OTUs),
            SE = se(Unique_OTUs),
            SD = sd(Unique_OTUs),
            Median = median(Unique_OTUs))
uniq.otus.sum$YMAX <- uniq.otus.sum$Mean + uniq.otus.sum$SE
uniq.otus.sum$YMIN <- uniq.otus.sum$Mean - uniq.otus.sum$SE

otu.ann <- data.frame(lab = c("*", " "), Group = factor(c("Summer_Captive", "Summer_Wild")))

otu.plot <- ggplot(uniq.otus, aes(x = Group, y = Unique_OTUs, fill = Group)) +
  geom_violin() +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1, stackratio = 1.15, fill = "black") +
  scale_fill_manual(values = c("#e60000", "#ec9393"), labels = c("Captive", "Wild")) +
  scale_y_continuous(limits = c(250,710), breaks = c(250, 340, 430, 520, 610, 700)) +
  scale_x_discrete(labels = c("Captive", "Wild")) +
  ylab("Number of Unique OTUs") +
    theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face="bold", size=6),
        strip.text.x = element_text(face ="bold", size=6),
        axis.title.x = element_text(face="bold", size=6),
        axis.title.y = element_text(face="bold", size=6),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6),
        legend.position = "none") +
  geom_text(data = otu.ann, aes(label=lab), x=c(1.5,0),
            y=c(705,0), size=5, color="black")






###### Faith's Phylogenetic Diversity ######

# Prepare PD ###
pd.ready <- merge(pd.stats, meta, by = "Sample")
pd.ready$Group <- ordered(pd.ready$Group, levels = c("Summer_Captive", "Summer_Wild"))
pd.sum <- pd.ready %>%
  group_by(Group) %>%
  summarize(Mean = mean(Stat),
            SE = se(Stat),
            SD = sd(Stat),
            Median = median(Stat))
pd.sum$YMAX <- pd.sum$Mean + pd.sum$SE
pd.sum$YMIN <- pd.sum$Mean - pd.sum$SE


pd.ann <- data.frame(lab = c("*", " "), Group = factor(c("Summer_Captive", "Summer_Wild")))

pd.plot <- ggplot(pd.ready, aes(x = Group, y = Stat, fill = Group)) +
  geom_violin() + 
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1, stackratio = 1.15, fill = "black") +
  scale_fill_manual(values = c("#e60000", "#ec9393"), labels = c("Captive", "Wild")) +
  scale_y_continuous(limits = c(16.5,37.5), breaks = c(16.5,20.5,24.5,28.5,32.5,36.5)) +
  scale_x_discrete(labels = c("Captive", "Wild")) +
  ylab("Faith's Phylogenetic Diversity") +
    theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face="bold", size=6),
        strip.text.x = element_text(face ="bold", size=6),
        axis.title.x = element_text(face="bold", size=6),
        axis.title.y = element_text(face="bold", size=6),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6),
        legend.position = "none") +
  geom_text(data = pd.ann, aes(label=lab), x=c(1.5,0),
            y=c(37,0), size=5, color="black")
  
  

        
###### Phylogenetic Evenness (MPD) ######

# Prepare MPD
mpd.ready <- merge(mpd.stats, meta, by = "Sample")
mpd.ready$Group <- ordered(mpd.ready$Group, levels = c("Summer_Captive", "Summer_Wild"))
mpd.sum <- mpd.ready %>%
  group_by(Group) %>%
  summarize(Mean = mean(Stat),
            SE = se(Stat),
            SD = sd(Stat),
            Median = median(Stat))
mpd.sum$YMAX <- mpd.sum$Mean + mpd.sum$SE
mpd.sum$YMIN <- mpd.sum$Mean - mpd.sum$SE

mpd.ann <- data.frame(lab = c("ns", " "), Group = factor(c("Summer_Captive", "Summer_Wild")))

mpd.plot <- ggplot(mpd.ready, aes(x = Group, y = Stat, fill = Group)) +
  geom_violin() +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1, stackratio = 1.15, fill = "black") +
  scale_fill_manual(values = c("#e60000", "#ec9393"), labels = c("Captive", "Wild")) +
  scale_y_continuous(limits = c(-6,6), breaks = c(-6,-4,-2,0,2,4,6)) +
  scale_x_discrete(labels = c("Captive", "Wild")) +
  ylab("Phylogenetic Evenness (MPD)") +
    theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face="bold", size=6),
        strip.text.x = element_text(face ="bold", size=6),
        axis.title.x = element_text(face="bold", size=6),
        axis.title.y = element_text(face="bold", size=6),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6),
        legend.position = "none") +
  geom_text(data = mpd.ann, aes(label=lab), x=c(1.5,0),
            y=c(6.2,0), size=2.5, color="black")
  

        

###### Shannon's Diversity #####      

# Prepare data for plot
shannon.sum <- adiv %>%
  group_by(Group) %>%
  summarize(Mean = mean(shannon),
            SE = se(shannon),
            SD = sd(shannon),
            Median = median(shannon))
shannon.sum$YMAX <- shannon.sum$Mean + shannon.sum$SE
shannon.sum$YMIN <- shannon.sum$Mean - shannon.sum$SE

shannon.ann <- data.frame(lab = c("ns", " "), Group = factor(c("Summer_Captive", "Summer_Wild")))


shannon.plot <- ggplot(adiv, aes(x = Group, y = shannon, fill = Group)) +
  geom_violin() +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1, stackratio = 1.15, fill = "black") +
  scale_fill_manual(values = c("#e60000", "#ec9393"), labels = c("Captive", "Wild")) +
  scale_y_continuous(limits = c(2.3,5.55), breaks = c(2.3,3.1,3.9,4.7,5.5)) +
  scale_x_discrete(labels = c("Captive", "Wild")) +
  ylab("Shannon's Diversity") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face="bold", size=6),
        strip.text.x = element_text(face ="bold", size=6),
        legend.title = element_text(face="bold", size=6),
        axis.title.x = element_text(face="bold", size=6),
        axis.title.y = element_text(face="bold", size=6),
        axis.text.x = element_text(size=6),
        axis.text.y = element_text(size=6),
        legend.text = element_text(size=6),
        legend.key.height = unit(3, 'mm'),
        legend.key.width = unit(3, "mm"),
        legend.box.margin=margin(-10,-10,-10,-10)) +
  geom_text(data = shannon.ann, aes(label=lab), x=c(1.5,0),
            y=c(5.6,0), size=2.5, color="black")




```


### Content - Plot - Alpha-Diversity
```{r}
tiff("wild.captive.con.adiv.tiff", width = 170, height = 60, units = "mm", res = 600)
grid.newpage()
pushViewport(viewport(layout=grid.layout(2,4, widths = c(1, 1, 1, 1.4), heights = c(0.07, 1.5))))
grid.text("A", x=unit(0.06, "npc"), vp=viewport(layout.pos.row=1, layout.pos.col=1),
          gp=gpar(fontsize=8,fontface="bold"))
print(otu.plot, vp=viewport(layout.pos.row=2, layout.pos.col=1))
grid.text("B", x=unit(0.06, "npc"), vp=viewport(layout.pos.row=1, layout.pos.col=2),
          gp=gpar(fontsize=8,fontface="bold"))
print(pd.plot, vp=viewport(layout.pos.row=2, layout.pos.col=2))
grid.text("C", x=unit(0.06, "npc"), vp=viewport(layout.pos.row=1, layout.pos.col=3),
          gp=gpar(fontsize=8,fontface="bold"))
print(mpd.plot, vp=viewport(layout.pos.row=2, layout.pos.col=3))
grid.text("D", x=unit(0.045, "npc"), vp=viewport(layout.pos.row=1, layout.pos.col=4),
          gp=gpar(fontsize=8,fontface="bold"))
print(shannon.plot, vp=viewport(layout.pos.row=2, layout.pos.col=4))
dev.off()
```
























### Beta Diversity
```{r}

########## Weighted UniFrac ##########
UF.w <- phyloseq::distance(physeq = physeq, method = "wunifrac")
UF.w.pcoa <- ordinate(physeq = physeq, method = "PCoA", distance = "wunifrac")
  # Variation explained = 34.9%

wUF.plot <- plot_ordination(physeq = physeq, ordination = UF.w.pcoa, axes = c(1,2),
                title = "Weighted UniFrac", color = "Group") +
  stat_ellipse(aes(colour = Group), size = 1, level = 0.95) +
  scale_colour_manual(values = c("#e60000", "#ec9393", "#1c41b0", "deepskyblue", "#74b300"), labels = c("Summer Wild", "Summer Lab", "Torpor", "IBA", "Spring")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        plot.title = element_text(hjust = 0.5, size = 10),
        legend.position = "none"
        )


### PERMANOVA ###
sampdf <- data.frame(sample_data(physeq))
beta.tax <- betadisper(d=UF.w, group=sampdf$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.004
anosim(UF.w, sampdf$Group, permutations = 9999)
  # p-value = 1e-04



# Separate out pairwise comparisons
phy.ws <- merge_phyloseq(physeq.wild, physeq.sum)
phy.st <- merge_phyloseq(physeq.sum, physeq.tor)
phy.si <- merge_phyloseq(physeq.sum, physeq.iba)
phy.sp <- merge_phyloseq(physeq.sum, physeq.spr)
phy.ti <- merge_phyloseq(physeq.tor, physeq.iba)
phy.tp <- merge_phyloseq(physeq.tor, physeq.spr)
phy.ip <- merge_phyloseq(physeq.iba, physeq.spr)
phy.wt <- merge_phyloseq(physeq.wild, physeq.tor)
phy.wi <- merge_phyloseq(physeq.wild, physeq.iba)
phy.wp <- merge_phyloseq(physeq.wild, physeq.spr)


# Summer Wild vs. Summer Lab
ws.w <- phyloseq::distance(physeq = phy.ws, method = "wunifrac")
sampdf.ws<- data.frame(sample_data(phy.ws))
beta.tax <- betadisper(d=ws.w, group=sampdf.ws$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.005
anosim(ws.w, sampdf.ws$Group, permutations = 9999)
  # p-value = 0.0039

# Summer Lab vs Torpor
st.w <- phyloseq::distance(physeq = phy.st, method = "wunifrac")
sampdf.st<- data.frame(sample_data(phy.st))
beta.tax <- betadisper(d=st.w, group=sampdf.st$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.906
anosim(st.w, sampdf.st$Group, permutations = 9999)
  # p-value = 1e-04


# Summer Lab vs IBA
si.w <- phyloseq::distance(physeq = phy.si, method = "wunifrac")
sampdf.si<- data.frame(sample_data(phy.si))
beta.tax <- betadisper(d=si.w, group=sampdf.si$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.502
anosim(si.w, sampdf.si$Group, permutations = 9999)
  # p-value = 1e-04


# Summer Lab vs Spring
sp.w <- phyloseq::distance(physeq = phy.sp, method = "wunifrac")
sampdf.sp<- data.frame(sample_data(phy.sp))
beta.tax <- betadisper(d=sp.w, group=sampdf.sp$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.188
anosim(sp.w, sampdf.sp$Group, permutations = 9999)
  # p-value = 0.0374


# Torpor vs IBA
ti.w <- phyloseq::distance(physeq = phy.ti, method = "wunifrac")
sampdf.ti<- data.frame(sample_data(phy.ti))
beta.tax <- betadisper(d=ti.w, group=sampdf.ti$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.48
anosim(ti.w, sampdf.ti$Group, permutations = 9999)
  # p-value = 0.7029

# Torpor vs Spring
tp.w <- phyloseq::distance(physeq = phy.tp, method = "wunifrac")
sampdf.tp<- data.frame(sample_data(phy.tp))
beta.tax <- betadisper(d=tp.w, group=sampdf.tp$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.159
anosim(tp.w, sampdf.tp$Group, permutations = 9999)
  # p-value = 2e-04

# IBA vs Spring
ip.w <- phyloseq::distance(physeq = phy.ip, method = "wunifrac")
sampdf.ip<- data.frame(sample_data(phy.ip))
beta.tax <- betadisper(d=ip.w, group=sampdf.ip$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.362
anosim(ip.w, sampdf.ip$Group, permutations = 9999)
  # p-value = 1e-04

# Summer Wild vs. Torpor
wt.w <- phyloseq::distance(physeq = phy.wt, method = "wunifrac")
sampdf.wt<- data.frame(sample_data(phy.wt))
beta.tax <- betadisper(d=wt.w, group=sampdf.wt$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.004
anosim(wt.w, sampdf.wt$Group, permutations = 9999)
  # p-value = 1e-04 

# Summer Wild vs. IBA
wi.w <- phyloseq::distance(physeq = phy.wi, method = "wunifrac")
sampdf.wi<- data.frame(sample_data(phy.wi))
beta.tax <- betadisper(d=wi.w, group=sampdf.wi$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.004
anosim(wi.w, sampdf.wi$Group, permutations = 9999)
  # p-value = 1e-04

# Summer Wild vs. Spring
wp.w <- phyloseq::distance(physeq = phy.wp, method = "wunifrac")
sampdf.wp<- data.frame(sample_data(phy.wp))
beta.tax <- betadisper(d=wp.w, group=sampdf.wp$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.078
anosim(wp.w, sampdf.wp$Group, permutations = 9999)
  # p-value = 5e-04


# Adjust betadisper p-values
p.adjust(c(0.001,0.906,0.502,0.188,0.48,0.159,0.362,0.004,0.004,0.078),
         method = "fdr")
  # Summer Wild vs. Summer Lab = 0.01*
  # Summer Lab vs. Torpor = 0.906
  # Summer Lab vs. IBA = 0.55778
  # Summer Lab vs. Spring = 0.3133
  # Torpor vs. IBA = 0.55778
  # Torpor vs. Spring = 0.3133
  # IBA vs. Spring = 0.51714286
  # Summer Wild vs. Torpor = 0.0133*
  # Summer Wild vs. IBA = 0.0133*
  # Summer Wild vs. Spring = 0.195

# Adjust ANOSIM p-values
p.adjust(c(0.0039,1e-04,1e-04,0.0374,0.7029,2e-04,1e-04,1e-04,1e-04,5e-04),
         method = "fdr")
  # Summer Wild vs. Summer Lab = 0.004875*
  # Summer Lab vs. Torpor = 0.0002*
  # Summer Lab vs. IBA = 0.0002*
  # Summer Lab vs. Spring = 0.041556*
  # Torpor vs. IBA = 0.7029
  # Torpor vs. Spring = 0.00033*
  # IBA vs. Spring = 0.0002*
  # Summer Wild vs. Torpor = 0.0002*
  # Summer Wild vs. IBA = 0.0002*
  # Summer Wild vs. Spring = 0.0007142857*






########## Unweighted UniFrac ##########
UF.u <- phyloseq::distance(physeq = physeq, method = "unifrac")
UF.u.pcoa <- ordinate(physeq = physeq, method = "PCoA", distance = "unifrac")
  # Variation explained = 22.4%

uUF.plot <- plot_ordination(physeq = physeq, ordination = UF.u.pcoa, axes = c(1,2),
                title = "Unweighted UniFrac", color = "Group") +
  stat_ellipse(aes(colour = Group), size = 1, level = 0.95) +
  scale_colour_manual(values = c("#e60000", "#ec9393", "#1c41b0", "deepskyblue", "#74b300"), labels = c("Summer Wild", "Summer Lab", "Torpor", "IBA", "Spring")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        plot.title = element_text(hjust = 0.5, size = 10),
        legend.position  = "none"
        )


### PERMANOVA ###
sampdf <- data.frame(sample_data(physeq))
beta.tax <- betadisper(d=UF.u, group=sampdf$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001
anosim(UF.u, sampdf$Group, permutations = 9999)
  # p-value = 1e-04 



# Separate out pairwise comparisons
#phy.ws <- merge_phyloseq(physeq.wild, physeq.sum)
#phy.st <- merge_phyloseq(physeq.sum, physeq.tor)
#phy.si <- merge_phyloseq(physeq.sum, physeq.iba)
#phy.sp <- merge_phyloseq(physeq.sum, physeq.spr)
#phy.ti <- merge_phyloseq(physeq.tor, physeq.iba)
#phy.tp <- merge_phyloseq(physeq.tor, physeq.spr)
#phy.ip <- merge_phyloseq(physeq.iba, physeq.spr)
#phy.wt <- merge_phyloseq(physeq.wild, physeq.tor)
#phy.wi <- merge_phyloseq(physeq.wild, physeq.iba)
#phy.wp <- merge_phyloseq(physeq.wild, physeq.spr)


# Summer Wild vs. Summer Lab
ws.u <- phyloseq::distance(physeq = phy.ws, method = "unifrac")
sampdf.ws<- data.frame(sample_data(phy.ws))
beta.tax <- betadisper(d=ws.u, group=sampdf.ws$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001
anosim(ws.u, sampdf.ws$Group, permutations = 9999)
  # p-value = 1e-04

# Summer Lab vs Torpor
st.u <- phyloseq::distance(physeq = phy.st, method = "unifrac")
sampdf.st<- data.frame(sample_data(phy.st))
beta.tax <- betadisper(d=st.u, group=sampdf.st$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.181
anosim(st.u, sampdf.st$Group, permutations = 9999)
  # p-value = 1e-04

# Summer Lab vs IBA
si.u <- phyloseq::distance(physeq = phy.si, method = "unifrac")
sampdf.si<- data.frame(sample_data(phy.si))
beta.tax <- betadisper(d=si.u, group=sampdf.si$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.244
anosim(si.u, sampdf.si$Group, permutations = 9999)
  # p-value = 1e-04

# Summer Lab vs Spring
sp.u <- phyloseq::distance(physeq = phy.sp, method = "unifrac")
sampdf.sp<- data.frame(sample_data(phy.sp))
beta.tax <- betadisper(d=sp.u, group=sampdf.sp$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.02
anosim(sp.u, sampdf.sp$Group, permutations = 9999)
  # p-value = 0.4146

# Torpor vs IBA
ti.u <- phyloseq::distance(physeq = phy.ti, method = "unifrac")
sampdf.ti<- data.frame(sample_data(phy.ti))
beta.tax <- betadisper(d=ti.u, group=sampdf.ti$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.922
anosim(ti.u, sampdf.ti$Group, permutations = 9999)
  # p-value = 0.1647

# Torpor vs Spring
tp.u <- phyloseq::distance(physeq = phy.tp, method = "unifrac")
sampdf.tp<- data.frame(sample_data(phy.tp))
beta.tax <- betadisper(d=tp.u, group=sampdf.tp$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.004
anosim(tp.u, sampdf.tp$Group, permutations = 9999)
  # p-value = 0.0012

# IBA vs Spring
ip.u <- phyloseq::distance(physeq = phy.ip, method = "unifrac")
sampdf.ip<- data.frame(sample_data(phy.ip))
beta.tax <- betadisper(d=ip.u, group=sampdf.ip$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.144
anosim(ip.u, sampdf.ip$Group, permutations = 9999)
  # p-value = 0.0122


# Summer Wild vs. Torpor
wt.u <- phyloseq::distance(physeq = phy.wt, method = "unifrac")
sampdf.wt<- data.frame(sample_data(phy.wt))
beta.tax <- betadisper(d=wt.u, group=sampdf.wt$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001
anosim(wt.u, sampdf.wt$Group, permutations = 9999)
  # p-value = 1e-04 

# Summer Wild vs. IBA
wi.u <- phyloseq::distance(physeq = phy.wi, method = "unifrac")
sampdf.wi<- data.frame(sample_data(phy.wi))
beta.tax <- betadisper(d=wi.u, group=sampdf.wi$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.002
anosim(wi.u, sampdf.wi$Group, permutations = 9999)
  # p-value = 1e-04 

# Summer Wild vs. Spring
wp.u <- phyloseq::distance(physeq = phy.wp, method = "unifrac")
sampdf.wp<- data.frame(sample_data(phy.wp))
beta.tax <- betadisper(d=wp.u, group=sampdf.wp$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.003
anosim(wp.u, sampdf.wp$Group, permutations = 9999)
  # p-value = 5e-04


# Adjust betadisper p-values
p.adjust(c(0.001,0.181,0.244,0.02,0.922,0.004,0.144,0.001,0.002,0.003),
         method = "fdr")
  # Summer Wild vs. Summer Lab = 0.005*
  # Summer Lab vs. Torpor = 0.22625
  # Summer Lab vs. IBA = 0.2711
  # Summer Lab vs. Spring = 0.0333*
  # Torpor vs. IBA = 0.9220
  # Torpor vs. Spring = 0.008*
  # IBA vs. Spring = 0.205714286
  # Summer Wild vs. Torpor = 0.005*
  # Summer Wild vs. IBA = 0.00667*
  # Summer Wild vs. Spring = 0.0075*


# Adjust ANOSIM p-values
p.adjust(c(1e-04,1e-04,1e-04,0.4146,0.1647,0.0012,0.0122,1e-04,1e-04,5e-04),
         method = "fdr")
  # Summer Wild vs. Summer Lab = 0.0002*
  # Summer Lab vs. Torpor = 0.0002*
  # Summer Lab vs. IBA = 0.0002*
  # Summer Lab vs. Spring = 0.4146
  # Torpor vs. IBA = 0.183
  # Torpor vs. Spring = 0.0017142857*
  # IBA vs. Spring = 0.01525*
  # Summer Wild vs. Torpor = 0.0002*
  # Summer Wild vs. IBA = 0.0002*
  # Summer Wild vs. Spring = 0.000833*







########## Bray-Curtis ##########
bray.pcoa <- ordinate(physeq=physeq, method="PCoA", distance="bray")
  # Variation explained = 27.4%

bc.plot <- plot_ordination(physeq=physeq, ordination=bray.pcoa, color="Group",
                           title = "Bray-Curtis Dissimilarity") +
  stat_ellipse(aes(colour = Group), size = 1, level = 0.95) +
  scale_colour_manual(values = c("#e60000", "#ec9393", "#1c41b0", "deepskyblue", "#74b300"), labels = c("Summer Wild", "Summer Lab", "Torpor", "IBA", "Spring")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        plot.title = element_text(hjust = 0.5, size = 10),
        legend.position = "none"
        #legend.title = element_text(size = 8, face = "bold"),
        #legend.text = element_text(size = 8),
        #legend.key.height = unit(4, 'mm'),
        #legend.box.margin=margin(-10,-10,-10,-10)
        )


ord.legend <- g_legend(bc.plot)


### TEST ###
sampdf <- data.frame(sample_data(physeq))
bray <- phyloseq::distance(physeq = physeq, method = "bray")
beta.tax <- betadisper(d = bray, group = sampdf$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.008
anosim(bray, sampdf$Group, permutations = 9999)
  # p-value = 1e-04


### Summer Wild vs. Summer Lab ###
sampdf.ws <- data.frame(sample_data(phy.ws))
bray.ws <- phyloseq::distance(physeq = phy.ws, method = "bray")
beta.tax <- betadisper(d = bray.ws, group = sampdf.ws$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.002
anosim(bray.ws, sampdf.ws$Group, permutations = 9999)
  # p-value = 1e-04


### Summer Wild vs. Torpor ###
sampdf.wt <- data.frame(sample_data(phy.wt))
bray.wt <- phyloseq::distance(physeq = phy.wt, method = "bray")
beta.tax <- betadisper(d = bray.wt, group = sampdf.wt$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.002
anosim(bray.wt, sampdf.wt$Group, permutations = 9999)
  # p-value = 1e-04


### Summer Wild vs. IBA ###
sampdf.wi <- data.frame(sample_data(phy.wi))
bray.wi <- phyloseq::distance(physeq = phy.wi, method = "bray")
beta.tax <- betadisper(d = bray.wi, group = sampdf.wi$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.047
anosim(bray.wi, sampdf.wi$Group, permutations = 9999)
  # p-value = 1e-04


### Summer Wild vs. Spring ###
sampdf.wp <- data.frame(sample_data(phy.wp))
bray.wp <- phyloseq::distance(physeq = phy.wp, method = "bray")
beta.tax <- betadisper(d = bray.wp, group = sampdf.wp$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.304
anosim(bray.wp, sampdf.wp$Group, permutations = 9999)
  # p-value = 8e-04


### Summer Lab vs. Torpor ###
sampdf.st <- data.frame(sample_data(phy.st))
bray.st <- phyloseq::distance(physeq = phy.st, method = "bray")
beta.tax <- betadisper(d = bray.st, group = sampdf.st$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.436
anosim(bray.st, sampdf.st$Group, permutations = 9999)
  # p-value = 1e-04


### Summer Lab vs. IBA ###
sampdf.si <- data.frame(sample_data(phy.si))
bray.si <- phyloseq::distance(physeq = phy.si, method = "bray")
beta.tax <- betadisper(d = bray.si, group = sampdf.si$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.221
anosim(bray.si, sampdf.si$Group, permutations = 9999)
  # p-value = 1e-04


### Summer Lab vs. Spring ###
sampdf.sp <- data.frame(sample_data(phy.sp))
bray.sp <- phyloseq::distance(physeq = phy.sp, method = "bray")
beta.tax <- betadisper(d = bray.sp, group = sampdf.sp$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.036
anosim(bray.sp, sampdf.sp$Group, permutations = 9999)
  # p-value = 0.0944


### Torpor vs. IBA ###
sampdf.ti <- data.frame(sample_data(phy.ti))
bray.ti <- phyloseq::distance(physeq = phy.ti, method = "bray")
beta.tax <- betadisper(d = bray.ti, group = sampdf.ti$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.556
anosim(bray.ti, sampdf.ti$Group, permutations = 9999)
  # p-value = 0.8569


### Torpor vs. Spring ###
sampdf.tp <- data.frame(sample_data(phy.tp))
bray.tp <- phyloseq::distance(physeq = phy.tp, method = "bray")
beta.tax <- betadisper(d = bray.tp, group = sampdf.tp$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.041
anosim(bray.tp, sampdf.tp$Group, permutations = 9999)
  # p-value = 2e-04


### IBA vs. Spring ###
sampdf.ip <- data.frame(sample_data(phy.ip))
bray.ip <- phyloseq::distance(physeq = phy.ip, method = "bray")
beta.tax <- betadisper(d = bray.ip, group = sampdf.ip$Group)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.255
anosim(bray.ip, sampdf.ip$Group, permutations = 9999)
  # p-value = 1e-04



### Adjust betadisper p-values
p.adjust(c(0.002, 0.002, 0.047, 0.304, 0.436, 0.221, 0.036, 0.556, 0.041, 0.255), 
         method = "fdr")
  # Summer Wild vs. Summer Lab = 0.01*
  # Summer Wild vs. Torpor = 0.01*
  # Summer Wild vs. IBA = 0.094
  # Summer Wild vs. Spring = 0.38
  # Summer Lab vs. Torpor = 0.4844
  # Summer Lab vs. IBA = 0.3642857
  # Summer Lab vs. Spring = 0.094
  # Torpor vs. IBA = 0.556
  # Torpor vs. Spring = 0.094
  # IBA vs. Spring = 0.364



### Adjust ANOSIM p-values
p.adjust(c(1e-04, 1e-04, 1e-04, 8e-04, 1e-04, 1e-04, 0.0944, 0.8569, 2e-04, 1e-04), 
         method = "fdr")
  # Summer Wild vs. Summer Lab = 0.0001667*
  # Summer Wild vs. Torpor = 0.0001667*
  # Summer Wild vs. IBA = 0.0001667*
  # Summer Wild vs. Spring = 0.001*
  # Summer Lab vs. Torpor = 0.0001667*
  # Summer Lab vs. IBA = 0.0001667*
  # Summer Lab vs. Spring = 0.104889
  # Torpor vs. IBA = 0.8569
  # Torpor vs. Spring = 0.0002857143*
  # IBA vs. Spring = 0.0001667*

```
